version: "3.8"

services:
  didar:
    image: didar-django:2022.09.28.dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REQUIREMENTS_FILE: "requirements.txt"
    command: ["sh", "/start.sh"]
    restart: always
    ports:
      - 8888:8888
    depends_on:
      - didar-db
    env_file:
      - .env
    volumes:
      - .:/home/didar/didar-backend
    networks:
      - didar-net

  didar-db:
    image: postgres:13.5
    restart: always
    env_file:
      - .env
    volumes:
      - didar_postgres_data_storage:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    networks:
      - didar-net

  didar-redis:
    image: redis:6.2
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - didar_redis_data:/data
    networks:
      - didar-net

  celery-worker:
    build: .
    command: celery -A didar.celery_conf worker --loglevel=info
    volumes:
      - .:/home/didar/didar-backend
    depends_on:
      - didar-redis
      - didar-db
    env_file:
      - .env
    networks:
      - didar-net
    tty: true
    stdin_open: true

  celery-beat:
    build: .
    command: celery -A didar.celery_conf beat --loglevel=info
    volumes:
      - .:/home/didar/didar-backend
    depends_on:
      - didar-redis
      - didar-db
    env_file:
      - .env
    networks:
      - didar-net
    tty: true
    stdin_open: true

volumes:
  didar_postgres_data_storage:
  didar_redis_data:

networks:
  didar-net:
#    external: true
